Repository adithyapaib/downloadTimeCalculator, pull requests merged in 2021-10, with the labels that each got.

#8 redesign frontend using tailwind
  assets/index.css
  assets/index.css.map
  assets/index.js
  assets/index.scss
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#17 added reload
  index.html
Labels: good first issue, hacktoberfest-accepted

#24 Add animation to submit button
  assets/style.css
  index.html
Labels: good first issue, wontfix, hacktoberfest-accepted

#55 Fixed Bugs Added Alert
  assets/index.js
Labels: good first issue, hacktoberfest-accepted

#53 Redesigned README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#44 Changed the background color of the button to green for dark mode.
  assets/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted, sed moment

#83 Submit button color reversion when dark mode is turned off.
  index.html
Labels: hacktoberfest-accepted

#80 update
  index.html
  indexonchange.html
Labels: hacktoberfest-accepted

#42 added topic add css on submit button
  Change the button color in dark mode/index.html
  add css on submit button/index.html
Labels: good first issue, hacktoberfest-accepted

#45 changed the colour and added shadow on hovering on submit button
  assets/style.css
Labels: good first issue, hacktoberfest-accepted

#95 Fixed submit button (issue #94)
  assets/helper.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#103 I fixed a bug that misaligned (autocalculate) and (Dark/Light mode)on each other
  index.html
Labels: hacktoberfest-accepted

#99 No collision with navbar issue solve and also some changes make code more effective also changes in js and css file.
  assets/style.css
  index.html
  newCodes/index.html
  newCodes/index.js
  newCodes/style.css
Labels: bug, good first issue, hacktoberfest-accepted, sed moment

#102 align items in navbar
  assets/style.css
  index.html
Labels: hacktoberfest-accepted

#98 aligning the navbar links issue #82
  index.html
Labels: good first issue, hacktoberfest-accepted

#97 Make changes in navbar and submit button and correction of hiding title in header.
  assets/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#92 Resolving issues #51 and #52
  assets/helper.css
  assets/index.js
  assets/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#91 changed the color of button in dark mode
  assets/helper.css
  assets/style.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#111 commit
  add css on submit button/index.html
Labels: good first issue, hacktoberfest-accepted

#129 added focus to input box to change its color
  assets/style.css
Labels: hacktoberfest-accepted

#135 submit button is now responsive
  assets/style.css
Labels: good first issue, hacktoberfest-accepted
